### PR TITLE
Add inference script

### PR DESCRIPTION
**Pull request by JCBrouwer**
Just a simple script to sample from a model.

I'd like to add video init (vid2vid) and [watermark removal](https://huggingface.co/spaces/fffiloni/lama-video-watermark-remover) later on as well.

### CODE REVIEW

**Comment by ExponentialML** [comment]
Thanks! I have one locally, but I'll merge this one. Just let me know when it's ready :+1: .

**Comment by JCBrouwer** [comment]
@ExponentialML alright, I've added watermark inpainting and video init functionality to the inference script, take a look and let me know what you think!

Here's some examples, the first generated with "a beautiful waterfall" and inpainted. The rest use that video as initialization with varying init_weight and prompt "cosmic nebula":

https://user-images.githubusercontent.com/15871226/230898480-092ac248-7f75-4d30-86ed-6536602f6f4d.mp4

init

https://user-images.githubusercontent.com/15871226/230898617-ea1bac69-6a29-4de5-9202-d2f488971ed1.mp4

0.6

https://user-images.githubusercontent.com/15871226/230898626-1d4b540c-c508-4774-8622-dd7d96894a14.mp4

0.5

https://user-images.githubusercontent.com/15871226/230898645-224a0bde-09c3-4f22-93e6-2edbc661dc69.mp4

0.4

https://user-images.githubusercontent.com/15871226/230898657-565bef4a-d227-4cfe-8f43-7a65f1aa14e1.mp4

0.3

https://user-images.githubusercontent.com/15871226/230898668-6467cad1-466d-45bf-85c7-55da61d083c8.mp4

0.2

https://user-images.githubusercontent.com/15871226/230898683-90232792-8030-471e-a9f6-348ddd234d14.mp4

0.1

**Comment by ExponentialML** [comment]
Excellent! I really appreciate your contribution :+1: .

**Comment by ExponentialML** [comment]
@JCBrouwer Forgot to add this before merging, but it's fine :slightly_smiling_face: . 

Could you add a section to the end of the `README` of the preferred ways using the inference script?

**Pull request merged**
