### PR TITLE
Convert diffusers to original MS format

### LINKED ISSUE #29: Using a trained model on webui
Is it possible?
Is there information that I should refer to anywhere?

### PR DESCRIPTION
**Pull request by kabachuha**
- [X] Convert the In/Out blocks
- [x] Convert the Text encoder
- [x] Convert Unet ResBlocks
- [x] Testing

closes #29

### CODE REVIEW

**Comment by kabachuha** [comment]
ModelStructure reference

[message.txt](https://github.com/ExponentialML/Text-To-Video-Finetuning/files/11249871/message.txt)

**Comment by kabachuha** [comment]
The conversion works!

```
python convert_diffusers_to_original_ms_text_to_video.py --model_path animov --checkpoint_path text2video_pytorch_model.pth --clip_checkpoint_path open_clip_pytorch_model.bin 
Initializing the conversion map
Converting the UNET
Saving UNET
Saving CLIP
Operation successfull
```

The only thing left is to load the model and see if it works

**Comment by kabachuha** [comment]
All complete


https://user-images.githubusercontent.com/14872007/232573270-74a96d38-d7a9-46be-9af9-3a25e966d2a3.mp4

**Comment by ExponentialML** [comment]
This was on my todo list, but you knocked it out of the park. Thank you very much!

**Comment by sanatorios** [comment]
This is amazing but I'm not really sure about the needed process. Would love to convert strangeman3107's animov-512x fine-tuned model into MS format as well. How it could be possiblle?

**Comment by howardgriffin** [comment]
Hi, I have noticed that the newest version(v3.0.0) of 'convert_diffusers_to_original_ms_text_to_video.py' doesn't save clip_checkpoint. 
What's more, this script doesn't save the config.json as  https://github.com/kabachuha/sd-webui-text2video mentioned.
So，I cann't test my own trained model with sd_webui. How to solve my problem?

**Pull request merged**
