### PR TITLE
Allow infinite-length generation

### PR DESCRIPTION
**Pull request by JCBrouwer**
Some major changes to the inference script that allow for generating videos that are longer than fit in memory (theoretically infinite, but not practically / quality-wise).

The idea is to work with a window and perform each step of the diffusion on all of the time-windows in the video before moving onto the next diffusion step. If you offset the windows so that they overlap, then the video comes out fairly coherent. It's a little bit of a hack, and leads to some abstract results (see some examples below).

From my testing, results are unchanged when --window-size is left to None, so people can choose whether they use this feature.

I've also gone ahead and added some text descriptions of all the inference parameters!

Here's some example results with Potat1:

txt2vid

https://github.com/ExponentialML/Text-To-Video-Finetuning/assets/15871226/eb2785cd-a792-4fcb-85f5-b631cea443f5

vid2vid

https://github.com/ExponentialML/Text-To-Video-Finetuning/assets/15871226/eaf5a4e1-e6e3-4c64-9bcb-cf5d12228fca

### CODE REVIEW

**Comment by JCBrouwer** [comment]
I think this might also address #69 and #74 

These models are definitely very sensitive to e.g. guidance scale and number of frames being rendered. This makes it hard to get good results, often leading to just noise with the wrong settings.

**Comment by ExponentialML** [comment]
Thanks for the PR! I'll be looking into all of the bugs and feature additions in the next week or so.

**Comment by JCBrouwer** [comment]
Cool!

I've been testing it out some more and the results for pure text2video aren't matching the old inference script yet.

I need to debug a little more before this is completely merge-ready, I think

**Comment by JCBrouwer** [comment]
Alright @ExponentialML, I've fixed a few more bugs and verified that now without windowed diffusion the outputs are pixel-for-pixel identical to the original pipeline.

As far as I'm concerned it's ready to be merged!

**Comment by ExponentialML** [comment]
> Alright @ExponentialML, I've fixed a few more bugs and verified that now without windowed diffusion the outputs are pixel-for-pixel identical to the original pipeline.
> 
> As far as I'm concerned it's ready to be merged!

Awesome, thanks for contributing!

**Pull request merged**
